services:
  pittica.prestashop.modules.feed.definition.factory.offer:
    class: 'Pittica\PrestaShop\Module\Feed\Grid\Definition\Factory\OfferDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    arguments:
      - "@=service('prestashop.adapter.shop.context').isAllShopContext()"

  pittica.prestashop.modules.feed.query_builder.product:
    class: 'Pittica\PrestaShop\Module\Feed\Grid\Query\OfferQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.shop.context').isAllShopContext()"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'

  pittica.prestashop.modules.feed.form.check.data_provider:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@pittica.prestashop.modules.feed.query_builder.product'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'pittica_feed_offer'

  pittica.prestashop.modules.feed.factory.offers:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@pittica.prestashop.modules.feed.definition.factory.offer'
      - '@pittica.prestashop.modules.feed.form.check.data_provider'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
