services:
  pittica.prestashop.modules.feed.form.configure.data_provider:
    class: 'Pittica\PrestaShop\Module\Feed\Form\DataProvider'
    arguments:
      - "@pittica.prestashop.modules.feed.form.configure.data_configuration"

  pittica.prestashop.modules.feed.form.configure.data_configuration:
    class: 'Pittica\PrestaShop\Module\Feed\Form\ConfigureDataConfiguration'
    parent: pittica.prestashop.modules.feed.form.data_configuration

  pittica.prestashop.modules.feed.form.configure.data_handler:
    class: PrestaShop\PrestaShop\Core\Form\Handler
    arguments:
      - "@form.factory"
      - "@prestashop.core.hook.dispatcher"
      - "@pittica.prestashop.modules.feed.form.configure.data_provider"
      - 'Pittica\PrestaShop\Module\Feed\Form\Type\ConfigureType'
      - "Configure"

  pittica.prestashop.modules.feed.form.type.configure:
    class: 'Pittica\PrestaShop\Module\Feed\Form\Type\ConfigureType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }
    arguments:
      - '@=service("prestashop.adapter.shop.context").isSingleShopContext()'
      - "@prestashop.adapter.data_provider.carrier"
